### PR TITLE
Fixed KeyError: 'Apps'

### PR DESCRIPTION
**Pull request by indykoning**
When running the script it crashed with "KeyError: 'Apps'" after dumping the contents of `sharedconfig[configstore]["Software"]["Valve"]["Steam"]` I noticed that apps is not uppercase so i changed the capital letters of Apps to uncapitalized.

### CODE REVIEW

**Comment by FruityWelsh** [comment]
It looks like the the tests also need to updated to pass the build test.

**Comment by CorruptComputer** [comment]
Ah, so if this is another difference I would much rather a detection system like the one done for ConfigStore, as a lot of people (including myself) have that key as "Apps" and "apps" will then cause errors for us.

**Comment by FruityWelsh** [comment]
Is it per system, or can one user have both Apps and apps?

**Comment by CorruptComputer** [comment]
It is most likely per system.

**Comment by FruityWelsh** [comment]
I thought of something. I am on the steam beta (Steam API: v018, package 1559784175). Let me revert back, maybe that is the change.

**Comment by CorruptComputer** [comment]
I am on the client beta as well, with my steam API and package being on the same version as yours. Steam is really strange with the differences in this file, as there is seemingly no rhyme or reason to it.

**Comment by FruityWelsh** [comment]
Weird.

**Comment by indykoning** [comment]
What distro are you two using? maybe that has impact on it? I'm using ubuntu 18.04.
Amended the commit to feature a test instead of changing the string.

**Comment by CorruptComputer** [comment]
I currently am using Manjaro. That may have an impact, I also just thought about this. Are you using the steam-runtime package or the steam-native package? That may have an impact as well.

**Comment by indykoning** [comment]
To be honest i don't know, the package name in Ubuntu is just `steam-launcher` :sweat_smile:

**Comment by indykoning** [comment]
I think [this](https://github.com/indykoning/ProtonDB-to-Steam-Library/commit/d278430531e0d46692722164c942e2bda1582aac#diff-38f7a0d0efffd3fd837baa5bec3070f8R45) may also be a cleaner solution to `get_configstore_for_vdf` as well since it doesn't depend on getting exceptions when trying to access data but instead it checks if the key exists on the array.

**Comment by CorruptComputer** [comment]
Yeah, that does seem to be a lot better of a solution. I can't merge it until a little later as I am currently at work, but this looks good to me! (at least reviewing it on my phone)

**Comment by FruityWelsh** [comment]
I'm on ubuntu 19.04.
Native steam from the ubuntu repo

**Comment by FruityWelsh** [comment]
The other I had was checking over the sharedconfig for capital letters, saving them off, changing them all to lower case, then after running through the code place back the changes.

To create a one size fits all option, so you can support more platforms.

**Comment by CorruptComputer** [comment]
I agree that future-proofing this would be a nice goal, however I would be afraid to make the code less readable with regex. For now as long as this helps get this working for people I think its fine.

**Pull request merged**
