### PR TITLE
Fixed request handling

### PR DESCRIPTION
**Pull request by dabura667**
json.load was giving a bunch of errors.

This is what finally got it working for me

### CODE REVIEW

**Comment by CorruptComputer** [comment]
What version of python are you using? You can check with `python --version`

**Comment by dabura667** [comment]
Python 3.5.2

**Comment by CorruptComputer** [comment]
Could you try using 3.7 to see if it works without this change?

**Comment by subwolf** [comment]
The changes make sense, the script as is assumes the json conversion will work. No harm in modifying to try/catch it.

**Comment by CorruptComputer** [comment]
Ah, I see now. I was trying to review this from my phone earlier and wasn't quite sure what it was doing. Taking another look at it, it looks good to me! :+1:

**Pull request merged**
